/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: operations["listTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get standings */
        get: operations["getStandings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season statistical leaders */
        get: operations["getLeaders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamID}/record-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team record over season */
        get: operations["getRecordTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamID}/season-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team season stats */
        get: operations["getTeamSeasonStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record-timelines/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch record timelines for many teams */
        get: operations["getRecordTimelinesBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/for-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Games scheduled for date */
        get: operations["getGamesForDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gamePk}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inning-by-inning game runs */
        get: operations["getGameTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gamePk}/boxscore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game boxscore */
        get: operations["getGameBoxscore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gamePk}/statcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game statcast batted balls */
        get: operations["getGameStatcast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gamePk}/statcast/pitches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game statcast pitch rows */
        get: operations["getGameStatcastPitches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player lookup by names string */
        get: operations["searchPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/current-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current team for two players (single request)
         * @description Same per-player data and cache behavior as GET /players/{playerID}/current-team, but fetches two ids in parallel. Response `players` order matches the `ids` query order.
         */
        get: operations["getPlayersCurrentTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{playerID}/current-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player current team */
        get: operations["getPlayerCurrentTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-player compare snapshot */
        get: operations["comparePlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/compare/year-by-year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-player year-by-year trend */
        get: operations["comparePlayersYearByYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/compare/game-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-player rolling game log */
        get: operations["comparePlayersGameLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/compare/platoon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-player platoon split comparison */
        get: operations["comparePlayersPlatoon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/league/season-baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** League baseline for season */
        get: operations["getLeagueSeasonBaseline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Human-readable error message
             * @example invalid season
             */
            error: string;
        };
        Team: {
            id: number;
            name: string;
            abbreviation: string;
            teamName: string;
            leagueId: number;
            leagueName: string;
            divisionId: number;
            divisionName: string;
            active: boolean;
        };
        TeamsResponse: {
            teams: components["schemas"]["Team"][];
        };
        StandingTeam: {
            teamId: number;
            teamName: string;
            wins: number;
            losses: number;
            pct: string;
            gamesPlayed: number;
            divisionRank: string;
            gamesBack: string;
            wildCardGamesBack?: string;
            runsScored?: number;
            runsAllowed?: number;
            runDifferential?: number;
            streak?: string;
            homeWins?: number;
            homeLosses?: number;
            awayWins?: number;
            awayLosses?: number;
            lastTenWins?: number;
            lastTenLosses?: number;
        };
        StandingDivision: {
            divisionId: number;
            divisionName: string;
            leagueId: number;
            teams: components["schemas"]["StandingTeam"][];
        };
        StandingsResponse: {
            season: number;
            divisions: components["schemas"]["StandingDivision"][];
        };
        RecordPoint: {
            gameIndex: number;
            officialDate: string;
            result: string;
            wins: number;
            losses: number;
            pct: number;
        };
        RecordTimelineResponse: {
            teamId: number;
            season: number;
            points: components["schemas"]["RecordPoint"][];
            finishedGames: number;
        };
        RecordTimelinesBatchResponse: {
            season: number;
            timelines: components["schemas"]["RecordTimelineResponse"][];
        };
        TeamSeasonStatsResponse: {
            season: number;
            teamId: number;
            hitting: components["schemas"]["TeamHittingLine"];
            pitching: components["schemas"]["TeamPitchingLine"];
            venueSplits: components["schemas"]["TeamVenueSplits"];
        };
        TeamVenueSplitLine: {
            games: number;
            wins: number;
            losses: number;
            runsScored: number;
            runsAllowed: number;
            runsPerGame?: number;
            runsAllowedPerGame?: number;
        };
        TeamVenueSplits: {
            home: components["schemas"]["TeamVenueSplitLine"];
            away: components["schemas"]["TeamVenueSplitLine"];
        };
        TeamHittingLine: {
            gamesPlayed: number;
            runs: number;
            runsPerGame: number;
            ops?: number;
            obp?: number;
            slg?: number;
            avg?: number;
            doubles: number;
            stolenBases: number;
            homeRuns?: number;
            homeRunsPerGame?: number;
            isolatedPower?: number;
            bbPct?: number;
            kPct?: number;
            babip?: number;
        };
        TeamPitchingLine: {
            gamesPlayed: number;
            runsAllowed: number;
            runsAllowedPerGame: number;
            era?: number;
            whip?: number;
            k9?: number;
            bb9?: number;
            hr9?: number;
            h9?: number;
            kbb?: number;
        };
        InningScore: {
            inning: number;
            homeRuns: number;
            awayRuns: number;
        };
        GameTimelineResponse: {
            gamePk: number;
            homeTeam: string;
            awayTeam: string;
            homeId: number;
            awayId: number;
            innings: components["schemas"]["InningScore"][];
            homeTotal: number;
            awayTotal: number;
        };
        TeamBoxSide: {
            teamId: number;
            teamName: string;
            totals: components["schemas"]["TeamGameTotals"];
            batting: components["schemas"]["BatterLine"][];
            pitching: components["schemas"]["PitcherLine"][];
        };
        TeamGameTotals: {
            runs: number;
            hits: number;
            errors: number;
            leftOnBase?: number;
            doubles?: number;
            triples?: number;
            homeRuns?: number;
        };
        BatterLine: {
            playerId: number;
            name: string;
            pos: string;
            ab: number;
            r: number;
            h: number;
            doubles: number;
            triples: number;
            hr: number;
            rbi: number;
            bb: number;
            so: number;
        };
        PitcherLine: {
            playerId: number;
            name: string;
            ip: string;
            h: number;
            r: number;
            er: number;
            bb: number;
            so: number;
            hr: number;
        };
        GameBoxscoreResponse: {
            gamePk: number;
            away: components["schemas"]["TeamBoxSide"];
            home: components["schemas"]["TeamBoxSide"];
        };
        GameStatcastResponse: {
            gamePk: number;
            venueId?: number;
            venueName?: string;
            battedBalls: components["schemas"]["StatcastBattedBall"][];
        };
        StatcastBattedBall: {
            launchSpeed?: number;
            launchAngle?: number;
            hcX?: number;
            hcY?: number;
            batter: number;
            pitcher: number;
            playerName: string;
            events?: string;
            inningHalf?: string;
        };
        GameStatcastPitchesResponse: {
            gamePk: number;
            pitches: components["schemas"]["StatcastPitch"][];
        };
        StatcastPitch: {
            plateX: number;
            plateZ: number;
            pitchName?: string;
            pitchType?: string;
            pitcher: number;
            releaseSpeed?: number;
            inningHalf?: string;
            szTop?: number;
            szBot?: number;
            /** @enum {string} */
            batterStand?: "L" | "R" | "S";
        };
        PlayerSearchHit: {
            id: number;
            fullName: string;
            position?: string;
            active: boolean;
            primaryNumber?: string;
        };
        PlayersSearchResponse: {
            query: string;
            people: components["schemas"]["PlayerSearchHit"][];
            truncated?: boolean;
        };
        PlayerCurrentTeamResponse: {
            playerId: number;
            teamId: number;
        };
        PlayersCurrentTeamsResponse: {
            players: components["schemas"]["PlayerCurrentTeamResponse"][];
        };
        PlayersRadarResponse: {
            /** @enum {string} */
            scope: "season" | "career";
            season: number;
            group: string;
            players: components["schemas"]["PlayerStatSnapshot"][];
        };
        PlayerStatSnapshot: {
            id: number;
            fullName: string;
            group: string;
            stats: {
                [key: string]: number;
            };
        };
        PlayersYearByYearResponse: {
            group: string;
            /** @enum {string} */
            metric: "ops" | "avg" | "obp" | "slg" | "woba" | "era" | "whip" | "k9" | "bb9" | "fip";
            players: components["schemas"]["YearSeriesPlayer"][];
            leagueBySeason: {
                [key: string]: number;
            };
        };
        YearSeriesPlayer: {
            id: number;
            fullName: string;
            points: components["schemas"]["SeasonPoint"][];
        };
        SeasonPoint: {
            season: number;
            value: number;
        };
        PlayersGameLogResponse: {
            season: number;
            group: string;
            /** @enum {string} */
            metric: "ops" | "era";
            limit: number;
            players: components["schemas"]["GameLogPlayer"][];
            leagueBaseline: number;
        };
        GameLogPlayer: {
            id: number;
            fullName: string;
            games: components["schemas"]["GamePoint"][];
        };
        GamePoint: {
            date: string;
            gamePk: number;
            value: number;
        };
        PlayersPlatoonResponse: {
            season: number;
            group: string;
            /** @enum {string} */
            metric: "ops";
            players: components["schemas"]["PlatoonPlayer"][];
        };
        PlatoonPlayer: {
            id: number;
            fullName: string;
            splits: components["schemas"]["PlatoonSplitRow"][];
        };
        PlatoonSplitRow: {
            code: string;
            description: string;
            ops: number;
            sample: number;
        };
        LeagueSeasonBaselineResponse: {
            season: number;
            group: string;
            ops: number;
            era: number;
        };
        GameSummary: {
            gamePk: number;
            awayTeam: string;
            homeTeam: string;
            awayId: number;
            homeId: number;
            status: string;
            awayScore: number;
            homeScore: number;
            officialDate?: string;
        };
        GamesForDateResponse: {
            date: string;
            games: components["schemas"]["GameSummary"][];
        };
        LeaderRow: {
            rank: number;
            value: string;
            /** Format: int64 */
            playerId: number;
            playerName: string;
            teamId: number;
            teamName: string;
            leagueName?: string;
        };
        LeadersResponse: {
            season: number;
            group: string;
            category: string;
            limit: number;
            leaders: components["schemas"]["LeaderRow"][];
            /** @description Allowlisted categories for the selected group */
            categories: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: {
                sportId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Teams list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamsResponse"];
                };
            };
        };
    };
    getStandings: {
        parameters: {
            query?: {
                season?: number;
                leagueId?: string;
                standingsTypes?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Division standings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream MLB failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLeaders: {
        parameters: {
            query?: {
                season?: number;
                /** @description hitting or pitching (default hitting) */
                group?: "hitting" | "pitching";
                /** @description Allowlisted MLB leaderCategories value for the group */
                category?: string;
                /** @description Max rows (1–25, default 10) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaders board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadersResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream MLB failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecordTimeline: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordTimelineResponse"];
                };
            };
        };
    };
    getTeamSeasonStats: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team season stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSeasonStatsResponse"];
                };
            };
        };
    };
    getRecordTimelinesBatch: {
        parameters: {
            query: {
                teamIds: string;
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record timelines batch */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordTimelinesBatchResponse"];
                };
            };
        };
    };
    getGamesForDate: {
        parameters: {
            query: {
                date: string;
                teamId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Games for date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesForDateResponse"];
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream MLB failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGameTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gamePk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameTimelineResponse"];
                };
            };
            /** @description Invalid gamePk */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream MLB failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGameBoxscore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gamePk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game boxscore */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameBoxscoreResponse"];
                };
            };
            /** @description Invalid gamePk */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Upstream MLB failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGameStatcast: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gamePk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statcast batted-ball events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatcastResponse"];
                };
            };
        };
    };
    getGameStatcastPitches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gamePk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statcast pitch rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatcastPitchesResponse"];
                };
            };
        };
    };
    searchPlayers: {
        parameters: {
            query: {
                names: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersSearchResponse"];
                };
            };
        };
    };
    getPlayersCurrentTeams: {
        parameters: {
            query: {
                /** @description Two comma-separated MLB person ids (distinct, positive). */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current team id per player */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersCurrentTeamsResponse"];
                };
            };
            /** @description Invalid or duplicate ids */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlayerCurrentTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playerID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current team id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCurrentTeamResponse"];
                };
            };
        };
    };
    comparePlayers: {
        parameters: {
            query: {
                ids: string;
                season?: number;
                group?: "hitting" | "pitching";
                scope?: "season" | "career";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player compare data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersRadarResponse"];
                };
            };
        };
    };
    comparePlayersYearByYear: {
        parameters: {
            query: {
                ids: string;
                group?: "hitting" | "pitching";
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Year-by-year values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersYearByYearResponse"];
                };
            };
        };
    };
    comparePlayersGameLog: {
        parameters: {
            query: {
                ids: string;
                season?: number;
                group?: "hitting" | "pitching";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player game log compare */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersGameLogResponse"];
                };
            };
        };
    };
    comparePlayersPlatoon: {
        parameters: {
            query: {
                ids: string;
                season?: number;
                group?: "hitting" | "pitching";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platoon split comparison */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayersPlatoonResponse"];
                };
            };
        };
    };
    getLeagueSeasonBaseline: {
        parameters: {
            query?: {
                season?: number;
                group?: "hitting" | "pitching";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League baseline values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueSeasonBaselineResponse"];
                };
            };
        };
    };
}
